
//! Autogenerated weights for `pallet_ghost_pqc`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2026-10-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `devin-box`, CPU: `INTEL(R) XEON(R) PLATINUM 8559C`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/ghost-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_ghost_pqc
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// /home/ubuntu/tmp/weights-pqc.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{constants::RocksDbWeight, Weight}};
use core::marker::PhantomData;

/// Weight functions for `pallet_ghost_pqc`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `GhostPqc::PqcKeys` (r:1 w:1)
	/// Proof: `GhostPqc::PqcKeys` (`max_values`: None, `max_size`: Some(2642), added: 5117, mode: `MaxEncodedLen`)
	fn register_pqc_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `6107`
		// Minimum execution time: 1_119_980_000 picoseconds.
		Weight::from_parts(1_144_254_000, 0)
			.saturating_add(Weight::from_parts(0, 6107))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `GhostPqc::PqcKeys` (r:1 w:1)
	/// Proof: `GhostPqc::PqcKeys` (`max_values`: None, `max_size`: Some(2642), added: 5117, mode: `MaxEncodedLen`)
	fn revoke_pqc_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `110`
		//  Estimated: `6107`
		// Minimum execution time: 11_301_000 picoseconds.
		Weight::from_parts(14_960_000, 0)
			.saturating_add(Weight::from_parts(0, 6107))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `GhostPqc::PqcKeys` (r:1 w:0)
	/// Proof: `GhostPqc::PqcKeys` (`max_values`: None, `max_size`: Some(2642), added: 5117, mode: `MaxEncodedLen`)
	/// Storage: `GhostConsensus::Bonded` (r:1 w:0)
	/// Proof: `GhostConsensus::Bonded` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn pqc_attest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2909`
		//  Estimated: `6107`
		// Minimum execution time: 1_126_599_000 picoseconds.
		Weight::from_parts(1_156_351_000, 0)
			.saturating_add(Weight::from_parts(0, 6107))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `GhostPqc::PqcRequired` (r:0 w:1)
	/// Proof: `GhostPqc::PqcRequired` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_pqc_required() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_290_000 picoseconds.
		Weight::from_parts(4_610_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests, delegating to RocksDb weights.
impl crate::WeightInfo for () {
	fn register_pqc_key() -> Weight {
		Weight::from_parts(1_144_254_000, 0)
			.saturating_add(Weight::from_parts(0, 6107))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn revoke_pqc_key() -> Weight {
		Weight::from_parts(14_960_000, 0)
			.saturating_add(Weight::from_parts(0, 6107))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn pqc_attest() -> Weight {
		Weight::from_parts(1_156_351_000, 0)
			.saturating_add(Weight::from_parts(0, 6107))
			.saturating_add(RocksDbWeight::get().reads(2))
	}
	fn set_pqc_required() -> Weight {
		Weight::from_parts(4_610_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
