//! Autogenerated weights for `pallet_ghost_pqc`
//!
//! THIS FILE WAS GENERATED BY AN IN-PALLET MEASUREMENT HARNESS — NOT by
//! `frame-benchmarking-cli` (the node `benchmark pallet` subcommand is not wired
//! yet; see `src/benchmarking.rs` → `mod measure`). Regenerate with:
//!
//! ```sh
//! GENERATE_WEIGHTS=1 rtk cargo test -p pallet-ghost-pqc \
//!     --features runtime-benchmarks --release -- --nocapture generate_weights
//! ```
//!
//! Caveats vs the canonical CLI flow — BEFORE any public-network weight claim,
//! re-run through the node `benchmark pallet` subcommand:
//!
//! * `ref_time` is native execution time (release build) — the Wasm interpreter
//!   is slower;
//! * `reads`/`writes` are unique storage keys touched, measured at the
//!   `Externalities` boundary — identical to what `sc-client-db`'s
//!   `BenchmarkState` reports;
//! * `proof_size` is a lower bound (data bytes of touched keys only — no trie
//!   branch nodes);
//! * `DbWeight` is read through `T::DbWeight` — the emitted file uses the
//!   runtime's configured DB weight at compile time of the consumer.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{constants::RocksDbWeight, Weight}};
use core::marker::PhantomData;

/// Weight functions for `pallet_ghost_pqc`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
    fn register_pqc_key() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `235`
        //  Estimated: `235`
        // Minimum execution time: 445_823_000 picoseconds.
        Weight::from_parts(486_221_000, 0)
            .saturating_add(Weight::from_parts(0, 235))
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    fn revoke_pqc_key() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `235`
        //  Estimated: `235`
        // Minimum execution time: 6_403_000 picoseconds.
        Weight::from_parts(6_762_000, 0)
            .saturating_add(Weight::from_parts(0, 235))
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    fn pqc_attest() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2829`
        //  Estimated: `2829`
        // Minimum execution time: 455_715_000 picoseconds.
        // NOTE: reads bumped 6 -> 7 post-benchmark — the bonded-validator
        // gate added a `pallet_ghost_consensus::Bonded` storage read.
        // Regenerate the benchmark to fold it into measured time.
        Weight::from_parts(489_303_000, 0)
            .saturating_add(Weight::from_parts(0, 2829))
            .saturating_add(T::DbWeight::get().reads(7))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn set_pqc_required() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `155`
        //  Estimated: `155`
        // Minimum execution time: 4_362_000 picoseconds.
        Weight::from_parts(4_568_000, 0)
            .saturating_add(Weight::from_parts(0, 155))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
}

impl crate::WeightInfo for () {
    fn register_pqc_key() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `235`
        //  Estimated: `235`
        // Minimum execution time: 445_823_000 picoseconds.
        Weight::from_parts(486_221_000, 0)
            .saturating_add(Weight::from_parts(0, 235))
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(4))
    }

    fn revoke_pqc_key() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `235`
        //  Estimated: `235`
        // Minimum execution time: 6_403_000 picoseconds.
        Weight::from_parts(6_762_000, 0)
            .saturating_add(Weight::from_parts(0, 235))
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(4))
    }

    fn pqc_attest() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2829`
        //  Estimated: `2829`
        // Minimum execution time: 455_715_000 picoseconds.
        // NOTE: reads bumped 6 -> 7 post-benchmark — the bonded-validator
        // gate added a `pallet_ghost_consensus::Bonded` storage read.
        Weight::from_parts(489_303_000, 0)
            .saturating_add(Weight::from_parts(0, 2829))
            .saturating_add(RocksDbWeight::get().reads(7))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn set_pqc_required() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `155`
        //  Estimated: `155`
        // Minimum execution time: 4_362_000 picoseconds.
        Weight::from_parts(4_568_000, 0)
            .saturating_add(Weight::from_parts(0, 155))
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
}
