//! Autogenerated weights for `pallet_ghost_consensus`
//!
//! Generated NATIVELY by the in-pallet measurement harness
//! (`mod measure` in `src/benchmarking.rs`) executing the real
//! generated `run_benchmark` over an instrumented in-memory state
//! backend — the `frame-benchmarking-cli` node subcommand is not
//! wired on this branch yet (see PR description for the follow-up).
//!
//! Command:
//!   GENERATE_WEIGHTS=1 rtk cargo test -p pallet-ghost-consensus \
//!     --features runtime-benchmarks --release -- --nocapture generate_weights
//!
//! Caveats vs a `frame-benchmarking-cli` run:
//!   * `ref_time` is native `std` execution on the generating host
//!     (see PR body for CPU/host); Wasm execution timing differs —
//!     regenerate via the CLI before any public-network claim.
//!   * DB read/write counts are Externalities-level key accesses.
//!   * `proof_size` = bytes of touched key+value data (measured
//!     lower bound; ignores trie-node hash overhead).


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_ghost_consensus`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
    fn bond() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `476`
        //  Estimated: `476`
        // Minimum execution time: 28_579_000 picoseconds.
        Weight::from_parts(31_144_000, 0)
            .saturating_add(Weight::from_parts(0, 476))
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }

    fn bond_extra() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `511`
        //  Estimated: `511`
        // Minimum execution time: 28_440_000 picoseconds.
        Weight::from_parts(28_983_000, 0)
            .saturating_add(Weight::from_parts(0, 511))
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }

    /// The range of component `u` is `[0, 3]`.
    fn unbond(u: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `357`
        //  Estimated: `357`
        // Minimum execution time: 7_505_000 picoseconds.
        Weight::from_parts(7_899_933, 0)
            .saturating_add(Weight::from_parts(0, 357))
            .saturating_add(Weight::from_parts(60_766, 0).saturating_mul((u).into()))
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
            .saturating_add(Weight::from_parts(0, 24).saturating_mul((u).into()))
    }

    /// The range of component `u` is `[1, 4]`.
    fn withdraw_unbonded(u: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `496`
        //  Estimated: `496`
        // Minimum execution time: 18_494_000 picoseconds.
        Weight::from_parts(19_744_500, 0)
            .saturating_add(Weight::from_parts(0, 496))
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
            .saturating_add(Weight::from_parts(0, 24).saturating_mul((u).into()))
    }

    /// The range of component `c` is `[0, 7]`.
    fn validate(c: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `333`
        //  Estimated: `333`
        // Minimum execution time: 6_343_000 picoseconds.
        Weight::from_parts(6_833_805, 0)
            .saturating_add(Weight::from_parts(0, 333))
            .saturating_add(Weight::from_parts(35_257, 0).saturating_mul((c).into()))
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
            .saturating_add(Weight::from_parts(0, 8).saturating_mul((c).into()))
    }

    /// The range of component `c` is `[0, 7]`.
    /// The range of component `v` is `[0, 2]`.
    fn chill(c: u32, v: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `237`
        //  Estimated: `237`
        // Minimum execution time: 6_306_000 picoseconds.
        Weight::from_parts(6_041_326, 0)
            .saturating_add(Weight::from_parts(0, 237))
            .saturating_add(Weight::from_parts(99_751, 0).saturating_mul((c).into()))
            .saturating_add(Weight::from_parts(315_579, 0).saturating_mul((v).into()))
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
            .saturating_add(Weight::from_parts(0, 8).saturating_mul((c).into()))
            .saturating_add(Weight::from_parts(0, 8).saturating_mul((v).into()))
    }

}
