
//! Autogenerated weights for `pallet_ghost_consensus`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2026-10-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `devin-box`, CPU: `INTEL(R) XEON(R) PLATINUM 8559C`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/ghost-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_ghost_consensus
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// /home/ubuntu/tmp/weights-consensus.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_ghost_consensus`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `GhostConsensus::Bonded` (r:1 w:1)
	/// Proof: `GhostConsensus::Bonded` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	fn bond() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `353`
		//  Estimated: `3593`
		// Minimum execution time: 51_143_000 picoseconds.
		Weight::from_parts(54_711_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `GhostConsensus::Bonded` (r:1 w:1)
	/// Proof: `GhostConsensus::Bonded` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	fn bond_extra() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `429`
		//  Estimated: `3593`
		// Minimum execution time: 47_520_000 picoseconds.
		Weight::from_parts(52_901_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `GhostConsensus::Bonded` (r:1 w:1)
	/// Proof: `GhostConsensus::Bonded` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `GhostConsensus::Unbonding` (r:1 w:1)
	/// Proof: `GhostConsensus::Unbonding` (`max_values`: None, `max_size`: Some(369), added: 2844, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[0, 15]`.
	fn unbond(_u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `307 + u * (20 ±0)`
		//  Estimated: `3834`
		// Minimum execution time: 15_165_000 picoseconds.
		Weight::from_parts(17_931_152, 0)
			.saturating_add(Weight::from_parts(0, 3834))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `GhostConsensus::Unbonding` (r:1 w:1)
	/// Proof: `GhostConsensus::Unbonding` (`max_values`: None, `max_size`: Some(369), added: 2844, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[1, 16]`.
	fn withdraw_unbonded(u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412 + u * (20 ±0)`
		//  Estimated: `3834`
		// Minimum execution time: 37_360_000 picoseconds.
		Weight::from_parts(39_706_221, 0)
			.saturating_add(Weight::from_parts(0, 3834))
			// Standard Error: 6_267
			.saturating_add(Weight::from_parts(14_213, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `GhostConsensus::Bonded` (r:1 w:0)
	/// Proof: `GhostConsensus::Bonded` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Session::NextKeys` (r:1 w:0)
	/// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `GhostPqc::PqcKeys` (r:1 w:0)
	/// Proof: `GhostPqc::PqcKeys` (`max_values`: None, `max_size`: Some(2642), added: 5117, mode: `MaxEncodedLen`)
	/// Storage: `GhostConsensus::Candidates` (r:1 w:1)
	/// Proof: `GhostConsensus::Candidates` (`max_values`: Some(1), `max_size`: Some(32770), added: 33265, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 1023]`.
	fn validate(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `583 + c * (32 ±0)`
		//  Estimated: `34255 + c * (32 ±0)`
		// Minimum execution time: 21_839_000 picoseconds.
		Weight::from_parts(22_719_371, 0)
			.saturating_add(Weight::from_parts(0, 34255))
			// Standard Error: 121
			.saturating_add(Weight::from_parts(27_725, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(c.into()))
	}
	/// Storage: `GhostConsensus::Candidates` (r:1 w:1)
	/// Proof: `GhostConsensus::Candidates` (`max_values`: Some(1), `max_size`: Some(32770), added: 33265, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 1023]`.
	fn chill(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `202 + c * (32 ±0)`
		//  Estimated: `34255`
		// Minimum execution time: 9_019_000 picoseconds.
		Weight::from_parts(9_368_663, 0)
			.saturating_add(Weight::from_parts(0, 34255))
			// Standard Error: 134
			.saturating_add(Weight::from_parts(26_569, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
